name: CI/CD Frontend
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
      
  test-frontend-and-sonar:
    name: Tester le frontend et analyser avec SonarCloud
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
    - name:  Récupérer le code source
      uses: actions/checkout@v2
    
    - name: Initialisation de Node.js 21
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Installation des dépendences
      run: npm install
      working-directory: front

    - name: Build de l'application
      run: npm run build

    - name: Exécution des tests unitaires et génération du rapport de couverture
      run: npm run test -- --code-coverage --no-progress --watch=false --browsers=ChromeHeadless
      working-directory: front

    - name: Upload du rapport de couverture
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: front/coverage/bobapp
        overwrite: true
        if-no-files-found: error

    - name: Scanner le code avec SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: front
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_FRONT }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_build_and_push:
    name: Build et Push l'image docker du frontend
    needs: test-frontend-and-sonar
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v4
      - name: Initialisation de Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
      - name: Connexion à Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build et Push l'image docker du frontend
        uses: docker/build-push-action@v6.2.0
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest